include: package:lints/recommended.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.pb.dart"
    - "**/*.pbenum.dart"
    - "**/*.pbjson.dart"
    - "**/*.pbserver.dart"
    - "**/generated/**"

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_expression_function_bodies: true
    prefer_single_quotes: true
    avoid_print: true
    use_colored_box: true
    use_decorated_box: true
    sized_box_for_whitespace: true
    unnecessary_string_interpolations: true
    prefer_interpolation_to_compose_strings: true
    require_trailing_commas: true
    use_build_context_synchronously: true
    avoid_unnecessary_containers: true
    prefer_relative_imports: true
    unawaited_futures: true
    cancel_subscriptions: true
    close_sinks: true
